cropper/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from photos.views import PhotoView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', PhotoView.as_view(), name='photos'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photos/models.py
from django.db import models
from django.urls import reverse

class Photo(models.Model):
	title = models.CharField(max_length=144)
	image = models.ImageField(
		upload_to='%Y/%m/%d/',
		height_field='image_height',
		width_field='image_width'
	)
	image_height = models.FloatField()
	image_width = models.FloatField()
	timestamp = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)

	def __str__(self):
		return str(self.title)

	def get_absolute_url(self):
		return reverse("photos:detail")

photos/forms.py
from django import forms
from django.core.files import File
from django.core.files.base import ContentFile

from PIL import Image
from io import BytesIO

from .models import Photo

class PhotoForm(forms.ModelForm):
	x = forms.FloatField(widget=forms.HiddenInput())
	y = forms.FloatField(widget=forms.HiddenInput())
	image_width = forms.FloatField(widget=forms.HiddenInput())
	image_height = forms.FloatField(widget=forms.HiddenInput())

	class Meta:
		model = Photo
		fields = ('title', 'image', 'x', 'y', 'image_height', 'image_width')

	def save(self, *args, **kwargs):
		photo = super(PhotoForm, self).save(commit=False)

		x = self.cleaned_data.get('x')
		y = self.cleaned_data.get('y')
		w = self.cleaned_data.get('image_width')
		h = self.cleaned_data.get('image_height')

		image = Image.open(photo.image)
		cropped_image = image.crop((x, y, w + x, h + y))
		resized_image = cropped_image.resize((200, 200), Image.ANTIALIAS)
		thumb_io = BytesIO()
		print(resized_image.format)
		resized_image.save(thumb_io, format=image.format)
		photo.save(image.filename, ContentFile(thumb_io.getvalue(), f'{image.filename}'))

		return super(PhotoForm, self).save(*args, **kwargs)

photos/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages

from .models import Photo
from .forms import PhotoForm

class PhotoView(View):
	def get(self, request):
		photos = Photo.objects.all()
		form = PhotoForm
		context = {
			'photos': photos,
			'form': form
		}
		return render(request, 'photos/photo_form.html', context)

	def post(self, request):
		form = PhotoForm(request.POST, request.FILES)
		if form.is_valid():
			form.save()
			messages.success(request, "Image has been saved")
			return redirect('photos')
		else:
			messages.error(request, "Correct the following errors")
			return redirect('photos')

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <title>{% block title %}Hello, world!{% endblock %}</title>

    {% block styles %}{% endblock %}
  </head>
  <body>
    {% block content %}

      <h1>Hello, world!</h1>

    {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>

    {% block scripts %}

    {% endblock scripts %}
  </body>
</html>

templates/photos/photo_form.html
{% extends "base.html" %}
{% load static %}

{% block styles %}

	<link  href="{% static 'css/cropper.min.css' %}" rel="stylesheet">
	<style type="text/css" media="screen">
		/* Limit image width to avoid overflow the container */
		img {
		  max-width: 100%; /* This rule is very important, please do not ignore this! */
		}
	</style>

{% endblock %}

{% block title %}

	Upload Photo

{% endblock %}

{% block content %}

<div class="container mt-5">
	<form method="post" enctype="multipart/form-data" id="formUpload">
  		{% csrf_token %}
  		{{ form.as_p }}
  		<button type="submit" id="formUploadButton" style="display: none;">Save</button>
	</form>

	<!-- MODAL TO CROP THE IMAGE -->
	<div class="modal fade" id="modalCrop">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	          <span aria-hidden="true">&times;</span>
	        </button>
	        <h4 class="modal-title">Crop the photo</h4>
	      </div>
	      <div class="modal-body">
	        <img src="" id="image" style="max-width: 100%;">
	      </div>
	      <div class="modal-footer">
	        <div class="btn-group pull-left" role="group">
	          <button type="button" class="btn btn-default js-zoom-in">
	            <span class="glyphicon glyphicon-zoom-in"></span>
	          </button>
	          <button type="button" class="btn btn-default js-zoom-out">
	            <span class="glyphicon glyphicon-zoom-out"></span>
	          </button>
	        </div>
	        <button type="button" class="btn btn-default" data-dismiss="modal">Nevermind</button>
	        <button type="button" class="btn btn-primary js-crop-and-upload">Crop and upload</button>
	      </div>
	    </div>
	  </div>
	</div>

	<!-- CONTAINER TO DISPLAY THE CROPPED IMAGES -->
	<div class="row mt-4">
	  {% for photo in photos %}
	    <div class="col-sm-4 col-md-3">
	    <a href="{{ photo.image.url }}" title="{{ photo.image }}">
	      	<img src="{{ photo.image.url }}" width="250" height="250" class="thumbnail">
	    </a>
	    </div>
	  {% endfor %}
	</div>

<!-- container ends here -->
</div>

{% endblock content %}

{% block scripts %}

	<script src="{% static 'js/cropper.min.js' %}"></script><!-- Cropper.js is required -->
    <script src="{% static 'js/jquery-cropper.min.js' %}"></script>

    <script type="text/javascript">

    $(function(){

    	/* SCRIPT TO OPEN THE MODAL WITH THE PREVIEW */
		$("#id_image").change(function (e) {
		  if (this.files && this.files[0]) {
		    var reader = new FileReader();
		    reader.onload = function (e) {
		      $("#image").attr("src", e.target.result);
		      $("#modalCrop").modal("show");
		    }
		    reader.readAsDataURL(this.files[0]);
		  }
		});

		/* SCRIPTS TO HANDLE THE CROPPER BOX */
		var $image = $("#image");
		var cropBoxData;
		var canvasData;
		$("#modalCrop").on("shown.bs.modal", function () {
		  $image.cropper({
		    viewMode: 1,
		    aspectRatio: 1/1,
		    minCropBoxWidth: 200,
		    minCropBoxHeight: 200,
		    ready: function () {
		      $image.cropper("setCanvasData", canvasData);
		      $image.cropper("setCropBoxData", cropBoxData);
		    }
		  });
		}).on("hidden.bs.modal", function () {
		  cropBoxData = $image.cropper("getCropBoxData");
		  canvasData = $image.cropper("getCanvasData");
		  $image.cropper("destroy");
		});

		// Enable zoom in button
		$(".js-zoom-in").click(function () {
		  $image.cropper("zoom", 0.1);
		});

		// Enable zoom out button
		$(".js-zoom-out").click(function () {
		  $image.cropper("zoom", -0.1);
		});

		/* SCRIPT TO COLLECT THE DATA AND POST TO THE SERVER */
		$(".js-crop-and-upload").click(function () {
		  var cropData = $image.cropper("getData");
		  $("#id_x").val(cropData["x"]);
		  $("#id_y").val(cropData["y"]);
		  $("#id_image_height").val(cropData["height"]);
		  $("#id_image_width").val(cropData["width"]);
		  $("#formUploadButton").click();
		});

	})
	</script>

{% endblock %}